### ISSUE TITLE
Users should not be able to remove the default state

### ISSUE THREAD

**Issue by cyruskurush** [KryptedGaming/krypted#291]
If an account has no groups, clicking on groups results in a 500 error
![chrome_j9A4wuq2e7](https://user-images.githubusercontent.com/60357056/73265856-bdeb2380-41a3-11ea-878b-a67d6a658ea0.png)
![chrome_MZFTWmSso2](https://user-images.githubusercontent.com/60357056/73265869-c6dbf500-41a3-11ea-8937-048dcb292931.png)

**Comment by porowns** [comment]
I need the error message from the logs of the container for this one

**Comment by KaiLister** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/krypted/app/group_requests/views.py", line 12, in view_groups
    valid_groups = get_valid_groups(request)
  File "/opt/krypted/app/group_requests/views.py", line 104, in get_valid_groups
    groups = Group.objects.filter(closedgroup__isnull=True, pk__in=request.user.state.get_all_enabling_groups())
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 415, in __get__
    self.related.get_accessor_name()
django.contrib.auth.models.User.state.RelatedObjectDoesNotExist: User has no state.

**Comment by porowns** [comment]
Very odd. Did you delete the default state with priority -1?

**Comment by cyruskurush** [comment]
There is no default state no, but that might also be why my new test accounts aren't getting placed in the appropriate groups based on corp

**Comment by cyruskurush** [comment]
Adding the default state fixed the issue

**Comment by KaiLister** [comment]
Group states was not a feature we had on when we started playing around.  It was added later. I don't remember seeing the default but its Cyrus just added it.

**Comment by porowns** [comment]
Can you delete the default state and restart your container? The default state should be automatically created

**Comment by KaiLister** [comment]
Ok, we can do that. Just the app container?. Also question with discord. Do we need to worry about running the jobs and having people suddenly removed from Discord during sync?

**Comment by porowns** [comment]
No, discord connector will only manage users that have connected their Discord
